#pragma once
// CPU-light offline steering; positional intent remains generated by the NPC's authored policy.
#include <algorithm>
#include <cmath>
namespace UnmadeCore {
struct Vec2 { double x = 0, y = 0; };
enum class NpcMotion { Stay, Approach, Retreat };
inline Vec2 SteerNpc(Vec2 current, Vec2 target, NpcMotion motion, double speedCmPerSecond,
                     double deltaSeconds, double stopRadiusCm) noexcept {
    if (motion == NpcMotion::Stay || !std::isfinite(current.x) || !std::isfinite(current.y)
        || !std::isfinite(target.x) || !std::isfinite(target.y)
        || !std::isfinite(speedCmPerSecond) || speedCmPerSecond <= 0
        || !std::isfinite(deltaSeconds) || deltaSeconds <= 0
        || !std::isfinite(stopRadiusCm) || stopRadiusCm < 0) return current;
    const double dx = target.x - current.x, dy = target.y - current.y;
    const double distance = std::hypot(dx,dy);
    if (!std::isfinite(distance)) return current;
    const double step = speedCmPerSecond * std::min(deltaSeconds, 0.25);
    if (motion == NpcMotion::Approach) {
        if (distance <= stopRadiusCm) return current;
        const double amount = std::min(step, distance - stopRadiusCm);
        return {current.x + dx / distance * amount, current.y + dy / distance * amount};
    }
    if (motion == NpcMotion::Retreat) {
        if (distance >= stopRadiusCm) return current;
        const double amount = std::min(step, stopRadiusCm - distance);
        return distance < 0.001 ? Vec2{current.x + amount, current.y}
             : Vec2{current.x - dx / distance * amount, current.y - dy / distance * amount};
    }
    return current;
}
}
