[/Script/EngineSettings.GameMapsSettings]
; Temporary built-in map until authored levels are produced in Unreal Editor.
EditorStartupMap=/Engine/Maps/Entry
GameDefaultMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/TheUnmadeGame.UnmadeGameMode

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_ThirdPerson",NewGameName="/Script/TheUnmadeGame")

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
